name: 'build-test'
on: # rebuild any PRs and main branch changes
  # push:
  workflow_dispatch:

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          dest-repo: https://gitee.com/zcong1993/actions-git-mirror.git
          dest-token: ${{ secrets.DEST_TOKEN }}
